// Map of place types to the pusheen image (/images/) they correspond to.
// https://developers.google.com/places/documentation/supported_types
var pusheenImages = {
	"aquarium": "petstore",
	"art_gallery": "sculptor",
	"bakery": "baker",
	"bar": "party",
	"bicycle_store": "bike",
	"book_store": "book",
	"cafe": "icecream",
	"car_dealer": "cars",
	"car_rental": "cars",
	"car_repair": "cars",
	"car_wash": "cars",
	"convenience_store": "eateverything",
	"department_store": "shopping",
	"food": "eateverything",
	"grocery_or_supermarket": "eateverything",
	"gym": "gym",
	"library": "book",
	"meal_delivery": "orderpizza",
	"meal_takeaway": "pizza",
	"museum": "sculptor",
	"night_club": "party",
	"park": "park",
	"parking": "cars",
	"pet_store": "petstore",
	"restaurant": "eateverything",
	"school": "book",
	"stadium": "basketball",
	"university": "book"
}